apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wpbpe3hxv-go 
  janus-idp.io/tekton: wpbpe3hxv-go
  backstage.io/kubernetes-id: wpbpe3hxv-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wpbpe3hxv-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  