apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wpbpe3hxv-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wpbpe3hxv-go 
  name: wpbpe3hxv-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wpbpe3hxv-go 
